apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: mariadb-server
spec:
  selector:
    app: mariadb-server
  type: LoadBalancer
  ports:
  - name: mariadb-port
    protocol: TCP
    port: 3306
    targetPort: 3306
  loadBalancerIP: 192.168.30.81 # from the MetalLB IP Pool