kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
  namespace: redis-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
